name = "chutirmart-website-final"
main = "server.ts"
compatibility_date = "2024-01-01"

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "chutirmart_db" 
# database_id = "your-database-id-goes-here" # আপনার Cloudflare D1 Database ID এখানে দিন
